server:
  port: 8005
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/aruneshjain/Microservice-config
          clone-on-start: true